# Generated by Django 5.2 on 2025-04-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmodel_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['-publish'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, unique_for_date='publish'),
        ),
    ]
