# Generated by Django 5.2 on 2025-04-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='blog.tagsmodel'),
        ),
    ]
